#!/bin/sh

set -e

raspbian_version="2019-07-10"

scriptdir=$(cd `dirname $0` && pwd)

(cd ${scriptdir}/docker-files-raspbian && ./prepare-raspbian-img.sh ${raspbian_version})

docker build --build-arg raspbian_version=${raspbian_version} -t mender-test-raspbian ${scriptdir}/docker-files-raspbian/

echo "Done!"
echo " you can start the DUT with \"docker run --network host mender-test-raspbian\""
echo " and access via SSH with \"ssh -p 8822 -i ${scriptdir}/docker-files/ssh-keys/key pi@localhost\""
